//
//  IODeviceProperties.swift
//  NumpadRemap
//
//  Created by David Belford on 9/25/18.
//  Copyright © 2018 David Belford. All rights reserved.
//

import Foundation
import IOKit.hid

public let deviceProperties = [
  kIOHIDTransportKey,
  kIOHIDVendorIDKey,
  kIOHIDVendorIDSourceKey,
  kIOHIDProductIDKey,
  kIOHIDVersionNumberKey,
  kIOHIDManufacturerKey,
  kIOHIDProductKey,
  kIOHIDSerialNumberKey,
  kIOHIDCountryCodeKey,
  kIOHIDStandardTypeKey,
  kIOHIDLocationIDKey,
  kIOHIDDeviceUsageKey,
  kIOHIDDeviceUsagePageKey,
  kIOHIDDeviceUsagePairsKey,
  kIOHIDPrimaryUsageKey,
  kIOHIDPrimaryUsagePageKey,
  kIOHIDMaxInputReportSizeKey,
  kIOHIDMaxOutputReportSizeKey,
  kIOHIDMaxFeatureReportSizeKey,
  kIOHIDReportIntervalKey,
  kIOHIDSampleIntervalKey,
  kIOHIDBatchIntervalKey,
  kIOHIDRequestTimeoutKey,
  kIOHIDReportDescriptorKey,
  kIOHIDResetKey,
  kIOHIDKeyboardLanguageKey,
  kIOHIDAltHandlerIdKey,
  kIOHIDBuiltInKey,
  kIOHIDDisplayIntegratedKey,
  kIOHIDProductIDMaskKey,
  kIOHIDProductIDArrayKey,
  kIOHIDPowerOnDelayNSKey,
  kIOHIDCategoryKey,
  kIOHIDMaxResponseLatencyKey,
  kIOHIDUniqueIDKey,
  kIOHIDPhysicalDeviceUniqueIDKey,
  kIOHIDTransportUSBValue,
  kIOHIDTransportBluetoothValue,
  kIOHIDTransportBluetoothLowEnergyValue,
  kIOHIDTransportAIDBValue,
  kIOHIDTransportI2CValue,
  kIOHIDTransportSPIValue,
  kIOHIDTransportSerialValue,
  kIOHIDTransportIAPValue,
  kIOHIDTransportAirPlayValue,
  kIOHIDTransportSPUValue,
  kIOHIDCategoryAutomotiveValue,
]

public let elementProperties = [
  kIOHIDElementKey,
  kIOHIDElementTypeKey,
  kIOHIDElementCollectionTypeKey,
  kIOHIDElementUsageKey,
  kIOHIDElementUsagePageKey,
  kIOHIDElementMinKey,
  kIOHIDElementMaxKey,
  kIOHIDElementScaledMinKey,
  kIOHIDElementScaledMaxKey,
  kIOHIDElementSizeKey,
  kIOHIDElementReportSizeKey,
  kIOHIDElementReportCountKey,
  kIOHIDElementReportIDKey,
  kIOHIDElementIsArrayKey,
  kIOHIDElementIsRelativeKey,
  kIOHIDElementIsWrappingKey,
  kIOHIDElementIsNonLinearKey,
  kIOHIDElementHasPreferredStateKey,
  kIOHIDElementHasNullStateKey,
  kIOHIDElementFlagsKey,
  kIOHIDElementUnitKey,
  kIOHIDElementUnitExponentKey,
  kIOHIDElementNameKey,
  kIOHIDElementValueLocationKey,
  kIOHIDElementDuplicateIndexKey,
  kIOHIDElementParentCollectionKey,
  kIOHIDElementVariableSizeKey,
  kIOHIDElementVendorSpecificKey,
  kIOHIDElementCookieMaxKey,
  kIOHIDElementUsageMinKey,
  kIOHIDElementUsageMaxKey,
  kIOHIDElementVendorSpecificKey
]
